#ifndef ARRS_CONSTANTS_H
#define ARRS_CONSTANTS_H

#define MAX_TICKET_COUNT 100
#define DEFAULT_RIDE_TIME 5
#define DEFAULT_RIDE_COUNT 5
#define REPOSITORY_INITIAL_CAPACITY 10
#define TICKET_FILE_PATH "ticket.txt"
#define RIDE_FILE_PATH "ride.txt"

#endif //ARRS_CONSTANTS_H